define("blockedTimeDetailsViewModel",["diagnosticsHub","diagnosticsHub-swimlanes","diagnosticsHub-ui","knockout","plugin-vs-v2"],((e,t,a,o,r)=>{return n={2608:e=>{const t=document.createElement("script");t.id="BlockedEventRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJ0cmVlR3JpZFJvdyBibG9ja2VkRXZlbnRSb3ciIHRhYmluZGV4PSItMSIgcm9sZT0icm93IiBkYXRhLWJpbmQ9InRyZWVHcmlkUm93Rm9jdXM6ICRwYXJlbnQuZm9jdXNlZFJvdygpID09PSAkZGF0YSwgY3NzOiB7IHNlbGVjdGVkOiBzZWxlY3RlZCgpIH0iPg0KICAgIDx0ZCBjbGFzcz0ibmFtZSIgcm9sZT0iZ3JpZGNlbGwiIGRhdGEtY29sdW1uaWQ9Im5hbWUiPg0KICAgICAgICA8c3BhbiBjbGFzcz0iaW5kZW50Ij4mbmJzcDs8L3NwYW4+DQogICAgPC90ZD4NCiAgICA8dGQgY2xhc3M9ImR1cmF0aW9uIiByb2xlPSJncmlkY2VsbCIgZGF0YS1iaW5kPSJ0ZXh0OiBkdXJhdGlvbkluTXMiIGRhdGEtY29sdW1uaWQ9ImR1cmF0aW9uIj48L3RkPg0KICAgIDx0ZCBjbGFzcz0ibWF4IiByb2xlPSJncmlkY2VsbCIgZGF0YS1jb2x1bW5pZD0ibWF4Ij48L3RkPg0KPC90cj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},7348:e=>{const t=document.createElement("script");t.id="BlockedThreadRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJ0cmVlR3JpZFJvdyIgdGFiaW5kZXg9Ii0xIiByb2xlPSJyb3ciIGRhdGEtYmluZD0idHJlZUdyaWRSb3dGb2N1czogJHBhcmVudC5mb2N1c2VkUm93KCkgPT09ICRkYXRhLCBjc3M6IHsgc2VsZWN0ZWQ6IHNlbGVjdGVkKCkgfSI+DQogICAgPHRkIGNsYXNzPSJuYW1lIGNvbnRhaW5lciIgcm9sZT0iZ3JpZGNlbGwiIGRhdGEtYmluZD0iY3NzOiB7IHNob3dUcmFja0FkZDogIXRyYWNrQWRkZWQoKSB9IiBkYXRhLWNvbHVtbmlkPSJuYW1lIj4NCiAgICAgICAgPGRpdiBkYXRhLWJpbmQ9InRyZWVHcmlkRXhwYW5kZXI6IGV4cGFuZGVkLCBzdHlsZTogeyB2aXNpYmlsaXR5OiBoYXNFdmVudHMgPyAndmlzaWJsZScgOiAnaGlkZGVuJyB9Ij48L2Rpdj4NCiAgICAgICAgPHNwYW4gZGF0YS1iaW5kPSJ0ZXh0OiBuYW1lIj48L3NwYW4+DQogICAgICAgIDxkaXYgY2xhc3M9ImJsb2NrZWRUaHJlYWQtYWRkVHJhY2siIGRhdGEtYmluZD0iY2xpY2s6IGFkZFRyYWNrLCB2aXNpYmxlOiAhdHJhY2tBZGRlZCgpIj48L2Rpdj4NCiAgICA8L3RkPg0KICAgIDx0ZCBjbGFzcz0iZHVyYXRpb24iIHJvbGU9ImdyaWRjZWxsIiBkYXRhLWJpbmQ9InRleHQ6IGR1cmF0aW9uSW5NcyIgZGF0YS1jb2x1bW5pZD0iZHVyYXRpb24iPjwvdGQ+DQogICAgPHRkIGNsYXNzPSJtYXgiIHJvbGU9ImdyaWRjZWxsIiBkYXRhLWJpbmQ9InRleHQ6IG1heEluTXMiIGRhdGEtY29sdW1uaWQ9Im1heCI+PC90ZD4NCjwvdHI+"),t.type="text/html",document.head.appendChild(t),e.exports={}},4816:function(e,t,a){var o,r,n=this&&this.__createBinding||(Object.create?function(e,t,a,o){void 0===o&&(o=a),Object.defineProperty(e,o,{enumerable:!0,get:function(){return t[a]}})}:function(e,t,a,o){void 0===o&&(o=a),e[o]=t[a]}),i=this&&this.__exportStar||function(e,t){for(var a in e)"default"===a||Object.prototype.hasOwnProperty.call(t,a)||n(t,e,a)};o=[a,t,a(3028),a(5639),a(4828),a(952),a(8117),a(8117)],r=function(e,t,a,o,r,n,d,s){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.getBlockedTimeDetailsViewModel=t.BlockedTimeDetailsViewModel=void 0,i(o,t);class l{constructor(){d.loadDataWarehouse().then((e=>{this._blockedTimeViewModel=new r.BlockedTimeViewModel(e),s.getViewEventManager().detailsViewReady.raiseEvent({Id:n.blockedTimeDetailsViewId()}),a.applyBindings(this)}))}get mainViewModel(){return this._blockedTimeViewModel}}let c;t.BlockedTimeDetailsViewModel=l,t.getBlockedTimeDetailsViewModel=function(){return c||(c=new l),c}}.apply(t,o),void 0===r||(e.exports=r)},4037:(e,t,a)=>{var o,r;o=[a,t,a(3028),a(8117),a(8117),a(2608)],r=function(e,t,a,o,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BlockedEventRowViewModel=void 0,t.BlockedEventRowViewModel=class{constructor(e,t){this._selected=a.observable(!1),this._expanded=a.observable(!1),this._dto=e,this._children=a.observableArray([]),this._parent=t}get parent(){return this._parent}get templateName(){return"BlockedEventRowView"}get id(){return this._dto.id}get depth(){return 1}get durationInMs(){return this._dto.durationInMs}get selected(){return this._selected}get expanded(){return this._expanded}get children(){return this._children}invoke(){r.getViewEventManager().selectionChanged.raiseEvent({position:new o.JsonTimespan(new o.BigNumber(this._dto.start.h,this._dto.start.l),new o.BigNumber(this._dto.end.h,this._dto.end.l)),isIntermittent:!1})}}}.apply(t,o),void 0===r||(e.exports=r)},7490:(e,t,a)=>{var o,r;o=[a,t,a(5226),a(3467),a(4881)],r=function(e,t,a,o,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BlockedStackFrame=void 0,t.BlockedStackFrame=class{constructor(e){this._dto=e}get name(){return this._dto.name}get label(){if(void 0===this._dto.jmcState)return"";switch(this._dto.jmcState){case r.JmcState.SystemCode:return a.Resources.getString("SystemCallLabel");case r.JmcState.LibraryCode:return a.Resources.getString("ExternalCallLabel");case r.JmcState.UserCode:default:return""}}get canGoToSource(){return this._dto.fileName&&"number"==typeof this._dto.lineNumber}goToSource(){return this.canGoToSource?(new o.BlockedTimeMarshaler).goToSource(this._dto.fileName,this._dto.lineNumber):Promise.resolve(!1)}}}.apply(t,o),void 0===r||(e.exports=r)},1336:(e,t,a)=>{var o,r;o=[a,t,a(3028),a(3467),a(4037),a(7348)],r=function(e,t,a,o,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BlockedThreadRowViewModel=void 0,t.BlockedThreadRowViewModel=class{constructor(e){this._selected=a.observable(!1),this._expanded=a.observable(!1),this._trackAdded=a.observable(!1),this._children=a.observableArray([]),this._haveLoaded=!1,this._marshaler=new o.BlockedTimeMarshaler,this._dto=e,this._marshaler.onTracksAdded.addEventListener((e=>{-1!==e.threadIds.indexOf(this._dto.threadId)&&this._trackAdded(!0)})),this._marshaler.onTracksRemoved.addEventListener((e=>{-1!==e.threadIds.indexOf(this._dto.threadId)&&this._trackAdded(!1)}))}get templateName(){return"BlockedThreadRowView"}get id(){return this._dto.threadId}get depth(){return 0}get name(){return this._dto.threadId.toString()}get durationInMs(){return this._dto.durationInMs}get maxInMs(){return this._dto.maxInMs}get trackAdded(){return this._trackAdded}get hasEvents(){return 0!==this._dto.durationInMs}get selected(){return this._selected}get expanded(){return this._expanded}get children(){return this._children}invoke(){}expand(e,t,a){let o=Promise.resolve();return this._haveLoaded||(this._haveLoaded=!0,o=e.getResult({op:"threadDetails",threadId:this._dto.threadId},a).then((e=>{const t=e.map((e=>new r.BlockedEventRowViewModel(e,this)));this._children(t)}))),this._expanded(!this._expanded()),o}addTrack(e,t){return this.trackAdded()||this._marshaler.addTrack(this._dto.threadId),!1}}}.apply(t,o),void 0===r||(e.exports=r)},5732:(e,t,a)=>{var o,r;o=[a,t,a(7490),a(952),a(1336)],r=function(e,t,a,o,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BlockedTimeDAO=void 0,t.BlockedTimeDAO=class{constructor(e){this._dataWarehouse=e}getRoots(e,t,a){return this._dataWarehouse.getFilteredData({customDomain:{Task:"Summary"}},o.blockedTimeAnalyzer(),a).then((e=>(a?.throwIfCancellationRequested(),this._currentResult=e,this._currentResult.getResult({op:"threadSummary"},a)))).then((e=>e.map((e=>new r.BlockedThreadRowViewModel(e)))))}sort(e,t,a){return Promise.resolve(e)}search(e,t,a,o,r,n,i){return Promise.resolve(null)}expand(e,t,a){return e.expand(this._currentResult,t,a)}queryStacks(e,t){return this._currentResult.getResult({op:"queryStacks",threadId:e.parent.id,eventId:e.id},t).then((e=>({blockedStack:e.blockedStack.map((e=>new a.BlockedStackFrame(e))),readyStack:e.readyStack.map((e=>new a.BlockedStackFrame(e)))})))}}}.apply(t,o),void 0===r||(e.exports=r)},3467:(e,t,a)=>{var o,r;o=[a,t,a(5226),a(8117)],r=function(e,t,a,o){"use strict";let r;Object.defineProperty(t,"__esModule",{value:!0}),t.BlockedTimeMarshaler=void 0,t.BlockedTimeMarshaler=class{constructor(){null===r&&(r=a.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.CpuSampling.BlockedTime.BlockedTimeMarshaler",{},!0)),this._onTracksAdded=new o.ObservableEvent(r,"onTracksAdded"),this._onTracksRemoved=new o.ObservableEvent(r,"onTracksRemoved")}get onTracksAdded(){return this._onTracksAdded}get onTracksRemoved(){return this._onTracksRemoved}addTrack(e){r._post("addTrack",e)}removeTrack(e){return r._call("removeTrack",e)}goToSource(e,t){return r._call("goToSource",e,t)}}}.apply(t,o),void 0===r||(e.exports=r)},7014:(e,t,a)=>{var o;o=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BlockedTimeSummaryColumnSettingsProvider=void 0,t.BlockedTimeSummaryColumnSettingsProvider=class{getColumnSettings(){return Promise.resolve([{columnId:"0",isHidden:!1,width:75},{columnId:"1",isHidden:!1,width:200},{columnId:"2",isHidden:!1,width:200}])}onColumnChanged(e){}}}.apply(t,[a,t]),void 0===o||(e.exports=o)},4828:(e,t,a)=>{var o,r;o=[a,t,a(5226),a(3028),a(4881),a(4881),a(4881),a(5732),a(7014),a(8117),a(952),a(8117)],r=function(e,t,a,o,r,n,i,d,s,l,c,u){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BlockedTimeViewModel=void 0,t.BlockedTimeViewModel=class{constructor(e){this._blockedStack=o.observableArray([]),this._readyStack=o.observableArray([]),this._dataLoadStatus=o.observable(r.DataLoadEvent.DataLoadCompleted),this._dataLoadPromise=null,this._dao=new d.BlockedTimeDAO(e);const t=new i.TreeGridHeaderViewModel([{id:"name",text:a.Resources.getString("BlockedTimeSummary_NameHeader"),hideable:!1},{id:"duration",text:a.Resources.getString("BlockedTimeSummary_DurationHeader"),hideable:!1},{id:"max",text:a.Resources.getString("BlockedTimeSummary_MaxHeader"),hideable:!1}],new s.BlockedTimeSummaryColumnSettingsProvider,"name");this._summaryViewModel=new n.TreeGridViewModel(this._dao,t,"BlockedTimeSummary_AriaLabel"),this._summaryViewModel.focusedRow.subscribe(this.onSelectionChanged.bind(this)),l.getViewEventManager().jmcEnabledStateChanged.addEventListener((()=>{this._summaryViewModel.onResultChanged(0)})),this._summaryViewModel.onResultChanged(0)}get summaryViewModel(){return this._summaryViewModel}get dataLoadStatus(){return this._dataLoadStatus}get blockedStack(){return this._blockedStack}get readyStack(){return this._readyStack}onSelectionChanged(e){if(null===e||!e.parent)return this._blockedStack([]),void this._readyStack([]);this._dataLoadCancellationTokenSource&&this._dataLoadCancellationTokenSource.cancel(),this._dataLoadCancellationTokenSource=new u.CancellationTokenSource,this._dataLoadCancellationTokenSource.token.onCancellationRequested.addEventListener((()=>{this._dataLoadStatus(r.DataLoadEvent.DataLoadCanceled)}),{once:!0});const t=e;this._dataLoadStatus(r.DataLoadEvent.DataLoadStart),this._dataLoadPromise=this._dao.queryStacks(t,this._dataLoadCancellationTokenSource.token).then((e=>{this._blockedStack(e.blockedStack),this._readyStack(e.readyStack)})).then((()=>{this._dataLoadPromise=null,this._dataLoadStatus(r.DataLoadEvent.DataLoadCompleted)}),(e=>{e.name!==c.errorNameCanceled()&&this._dataLoadStatus(r.DataLoadEvent.DataLoadFailed)}))}}}.apply(t,o),void 0===r||(e.exports=r)},952:(e,t,a)=>{var o;o=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.flameGraphViewModelMappingKey=t.flatFunctionsViewModelMappingKey=t.modulesViewModelMappingKey=t.callTreeViewModelMappingKey=t.callerCalleeViewModelMappingKey=t.functionLimit=t.defaultSampleRate=t.errorNameCanceled=t.blockedTimeDetailsViewId=t.performanceDebuggerDetailsViewId=t.collectionDetailsViewId=t.analysisDetailsViewId=t.blockedTimeAnalyzer=t.cpuSamplingAnalyzer=void 0,t.cpuSamplingAnalyzer=function(){return"DCA8B3EF-28C5-4B08-BAFC-B072F8AA9277"},t.blockedTimeAnalyzer=function(){return"3BA86369-05EE-409B-B598-BCCDFA4EFE2F"},t.analysisDetailsViewId=function(){return"7D95F423-6D5E-488C-B3A9-169D6D297D5C"},t.collectionDetailsViewId=function(){return"DDEDFB2B-8979-4CA9-BED3-7A3E4C495F1C"},t.performanceDebuggerDetailsViewId=function(){return"47660699-1BCE-4442-AEA7-A520683BDA66"},t.blockedTimeDetailsViewId=function(){return"CA734335-A674-41E2-BC61-98564E300942"},t.errorNameCanceled=function(){return"Canceled"},t.defaultSampleRate=function(){return 1e3},t.functionLimit=function(){return 5},t.callerCalleeViewModelMappingKey=function(){return"CallerCalleeView"},t.callTreeViewModelMappingKey=function(){return"CallTreeView"},t.modulesViewModelMappingKey=function(){return"ModulesView"},t.flatFunctionsViewModelMappingKey=function(){return"FlatFunctionsView"},t.flameGraphViewModelMappingKey=function(){return"FlameGraphView"}}.apply(t,[a,t]),void 0===o||(e.exports=o)},5639:(e,t,a)=>{var o,r;o=[a,t,a(8558)],r=function(e,t,a){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),window.CpuSamplingUI_onAfterDomInsert=a.onAfterDomInsert}.apply(t,o),void 0===r||(e.exports=r)},7886:(e,t,a)=>{var o;o=function(e,t){"use strict";var a,o,r,n,i,d,s,l;Object.defineProperty(t,"__esModule",{value:!0}),t.PerformanceSessionEntryPoint=t.SortColumn=t.CpuToolView=t.ResultStage=t.ResultNotStartedReason=t.ResultPreparationStatus=t.ActivityType=t.ResultTaskType=void 0,(l=t.ResultTaskType||(t.ResultTaskType={}))[l.Expand=1]="Expand",l[l.Search=2]="Search",l[l.GetData=3]="GetData",l[l.Sort=4]="Sort",l[l.ExpandHotPath=5]="ExpandHotPath",l[l.TopFunctions=6]="TopFunctions",l[l.GetNodePath=7]="GetNodePath",l[l.TopInsights=8]="TopInsights",l[l.Autocomplete=9]="Autocomplete",l[l.UpdateRoot=10]="UpdateRoot",l[l.InsightHelp=11]="InsightHelp",l[l.RequestHelp=12]="RequestHelp",l[l.AddSourceThenRequestHelp=13]="AddSourceThenRequestHelp",l[l.GetInsightFunc=14]="GetInsightFunc",(s=t.ActivityType||(t.ActivityType={}))[s.Unknown=0]="Unknown",s[s.ThreadRun=1]="ThreadRun",s[s.AsyncTask=2]="AsyncTask",(d=t.ResultPreparationStatus||(t.ResultPreparationStatus={}))[d.NotStarted=0]="NotStarted",d[d.InProgress=1]="InProgress",d[d.Completed=2]="Completed",d[d.Canceled=3]="Canceled",d[d.Failed=4]="Failed",(i=t.ResultNotStartedReason||(t.ResultNotStartedReason={}))[i.Unknown=0]="Unknown",i[i.NoValidTimeSelection=1]="NoValidTimeSelection",i[i.NoValidThreadSelection=2]="NoValidThreadSelection",i[i.ToolIsDisabled=3]="ToolIsDisabled",i[i.TargetRunningUnderDebugger=4]="TargetRunningUnderDebugger",(n=t.ResultStage||(t.ResultStage={}))[n.Unknown=0]="Unknown",n[n.Threads=1]="Threads",n[n.Sampling=2]="Sampling",(r=t.CpuToolView||(t.CpuToolView={}))[r.FlatFunctionsView=1]="FlatFunctionsView",r[r.CallerCalleeView=2]="CallerCalleeView",r[r.CallTreeView=3]="CallTreeView",r[r.ModulesView=4]="ModulesView",r[r.FlameGraphView=5]="FlameGraphView",(o=t.SortColumn||(t.SortColumn={}))[o.Id=1]="Id",o[o.FunctionName=2]="FunctionName",o[o.TotalSamples=3]="TotalSamples",o[o.SelfSamples=4]="SelfSamples",o[o.ModuleName=5]="ModuleName",o[o.CategoryName=6]="CategoryName",o[o.CallCount=7]="CallCount",(a=t.PerformanceSessionEntryPoint||(t.PerformanceSessionEntryPoint={}))[a.Profiling=0]="Profiling",a[a.PerformanceDebugger=1]="PerformanceDebugger"}.apply(t,[a,t]),void 0===o||(e.exports=o)},8558:(e,t,a)=>{var o,r;o=[a,t,a(5226),a(3028),a(7886),a(4881),a(8117),a(2560)],r=function(e,t,a,o,r,n,i,d){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.onAfterDomInsert=t.localizeNumber=t.areToolContextsEqual=t.areTimespansEqual=t.areBigNumbersEqual=t.numberComparator=t.getSortFunction=void 0;let s={};a.Culture.addEventListener("culturechanged",(()=>{s={}})),t.getSortFunction=function(e,t){switch(e){case r.SortColumn.Id:return n.SortFunctions.numericSort("id",t);case r.SortColumn.FunctionName:return n.SortFunctions.stringSort("name",t);case r.SortColumn.SelfSamples:return n.SortFunctions.numericSort("selfSamples",t);case r.SortColumn.TotalSamples:return n.SortFunctions.numericSort("totalSamples",t);case r.SortColumn.ModuleName:return n.SortFunctions.stringSort("moduleName",t);case r.SortColumn.CategoryName:return n.SortFunctions.stringSort("categoryName",t);case r.SortColumn.CallCount:return n.SortFunctions.numericSort("callCount",t);default:throw i.Assert.fail(`Unknown sort column: ${r.SortColumn[e]}`),new Error(`Unknown sort column: ${r.SortColumn[e]}`)}},t.numberComparator=function(e,t){return e-t},t.areBigNumbersEqual=function(e,t){return!e&&!t||e&&t&&e.h===t.h&&e.l===t.l},t.areTimespansEqual=function(e,t){return!e&&!t||e&&t&&e.equals(t)},t.areToolContextsEqual=function(e,t){return!e&&!t||e&&t&&e.rowId===t.rowId&&e.rowType===t.rowType},t.localizeNumber=function(e,t){const o=JSON.stringify(t||{});let r=s[o];if(!r){const e=new Intl.NumberFormat(a.Culture.formatRegion,t);r=t=>e.format(t),s[o]=r}return r(e)},t.onAfterDomInsert=function(){const e=document.getElementById("mainToolbar"),t=o.utils.domData.get(e,"mediaQuery");if(t){const a=o.utils.domData.get(e,"mediaQueryListener");t.removeListener(a)}let a=45;const r=e.children;for(let e=0;e<r.length;e++)a+=r.item(e).offsetWidth;const n=t=>{t.matches?e.classList.add("limitedSpace"):e.classList.remove("limitedSpace")},i=window.matchMedia(d.Utilities.formatString("(max-width: {0}px)",a.toString()));n(i),i.addListener(n),o.utils.domData.set(e,"mediaQuery",i),o.utils.domData.set(e,"mediaQueryListener",n)}}.apply(t,o),void 0===r||(e.exports=r)},8117:t=>{"use strict";t.exports=e},2560:e=>{"use strict";e.exports=t},4881:e=>{"use strict";e.exports=a},3028:e=>{"use strict";e.exports=o},5226:e=>{"use strict";e.exports=r}},i={},function e(t){var a=i[t];if(void 0!==a)return a.exports;var o=i[t]={exports:{}};return n[t].call(o.exports,o,o.exports,e),o.exports}(4816);var n,i}));
// SIG // Begin signature block
// SIG // MIIoRAYJKoZIhvcNAQcCoIIoNTCCKDECAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // +qXEajWM5YqLBKQqWnBs+i+UI0hQnQz+u8AnEvMCa+Og
// SIG // gg12MIIF9DCCA9ygAwIBAgITMwAABARsdAb/VysncgAA
// SIG // AAAEBDANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTI0MDkxMjIwMTExNFoX
// SIG // DTI1MDkxMTIwMTExNFowdDELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // tCg32mOdDA6rBBnZSMwxwXegqiDEUFlvQH9Sxww07hY3
// SIG // w7L52tJxLg0mCZjcszQddI6W4NJYb5E9QM319kyyE0l8
// SIG // EvA/pgcxgljDP8E6XIlgVf6W40ms286Cr0azaA1f7vaJ
// SIG // jjNhGsMqOSSSXTZDNnfKs5ENG0bkXeB2q5hrp0qLsm/T
// SIG // WO3oFjeROZVHN2tgETswHR3WKTm6QjnXgGNj+V6rSZJO
// SIG // /WkTqc8NesAo3Up/KjMwgc0e67x9llZLxRyyMWUBE9co
// SIG // T2+pUZqYAUDZ84nR1djnMY3PMDYiA84Gw5JpceeED38O
// SIG // 0cEIvKdX8uG8oQa047+evMfDRr94MG9EWwIDAQABo4IB
// SIG // czCCAW8wHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYB
// SIG // BQUHAwMwHQYDVR0OBBYEFPIboTWxEw1PmVpZS+AzTDwo
// SIG // oxFOMEUGA1UdEQQ+MDykOjA4MR4wHAYDVQQLExVNaWNy
// SIG // b3NvZnQgQ29ycG9yYXRpb24xFjAUBgNVBAUTDTIzMDAx
// SIG // Mis1MDI5MjMwHwYDVR0jBBgwFoAUSG5k5VAF04KqFzc3
// SIG // IrVtqMp1ApUwVAYDVR0fBE0wSzBJoEegRYZDaHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jcmwvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNybDBhBggr
// SIG // BgEFBQcBAQRVMFMwUQYIKwYBBQUHMAKGRWh0dHA6Ly93
// SIG // d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY2VydHMvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNydDAMBgNV
// SIG // HRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4ICAQCI5g/S
// SIG // KUFb3wdUHob6Qhnu0Hk0JCkO4925gzI8EqhS+K4umnvS
// SIG // BU3acsJ+bJprUiMimA59/5x7WhJ9F9TQYy+aD9AYwMtb
// SIG // KsQ/rst+QflfML+Rq8YTAyT/JdkIy7R/1IJUkyIS6srf
// SIG // G1AKlX8n6YeAjjEb8MI07wobQp1F1wArgl2B1mpTqHND
// SIG // lNqBjfpjySCScWjUHNbIwbDGxiFr93JoEh5AhJqzL+8m
// SIG // onaXj7elfsjzIpPnl8NyH2eXjTojYC9a2c4EiX0571Ko
// SIG // mhENF3RtR25A7/X7+gk6upuE8tyMy4sBkl2MUSF08U+E
// SIG // 2LOVcR8trhYxV1lUi9CdgEU2CxODspdcFwxdT1+G8YNc
// SIG // gzHyjx3BNSI4nOZcdSnStUpGhCXbaOIXfvtOSfQX/UwJ
// SIG // oruhCugvTnub0Wna6CQiturglCOMyIy/6hu5rMFvqk9A
// SIG // ltIJ0fSR5FwljW6PHHDJNbCWrZkaEgIn24M2mG1M/Ppb
// SIG // /iF8uRhbgJi5zWxo2nAdyDBqWvpWxYIoee/3yIWpquVY
// SIG // cYGhJp/1I1sq/nD4gBVrk1SKX7Do2xAMMO+cFETTNSJq
// SIG // fTSSsntTtuBLKRB5mw5qglHKuzapDiiBuD1Zt4QwxA/1
// SIG // kKcyQ5L7uBayG78kxlVNNbyrIOFH3HYmdH0Pv1dIX/Mq
// SIG // 7avQpAfIiLpOWwcbjzCCB3owggVioAMCAQICCmEOkNIA
// SIG // AAAAAAMwDQYJKoZIhvcNAQELBQAwgYgxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBSb290
// SIG // IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDExMB4XDTEx
// SIG // MDcwODIwNTkwOVoXDTI2MDcwODIxMDkwOVowfjELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjEoMCYGA1UEAxMfTWljcm9zb2Z0
// SIG // IENvZGUgU2lnbmluZyBQQ0EgMjAxMTCCAiIwDQYJKoZI
// SIG // hvcNAQEBBQADggIPADCCAgoCggIBAKvw+nIQHC6t2G6q
// SIG // ghBNNLrytlghn0IbKmvpWlCquAY4GgRJun/DDB7dN2vG
// SIG // EtgL8DjCmQawyDnVARQxQtOJDXlkh36UYCRsr55JnOlo
// SIG // XtLfm1OyCizDr9mpK656Ca/XllnKYBoF6WZ26DJSJhIv
// SIG // 56sIUM+zRLdd2MQuA3WraPPLbfM6XKEW9Ea64DhkrG5k
// SIG // NXimoGMPLdNAk/jj3gcN1Vx5pUkp5w2+oBN3vpQ97/vj
// SIG // K1oQH01WKKJ6cuASOrdJXtjt7UORg9l7snuGG9k+sYxd
// SIG // 6IlPhBryoS9Z5JA7La4zWMW3Pv4y07MDPbGyr5I4ftKd
// SIG // gCz1TlaRITUlwzluZH9TupwPrRkjhMv0ugOGjfdf8NBS
// SIG // v4yUh7zAIXQlXxgotswnKDglmDlKNs98sZKuHCOnqWbs
// SIG // YR9q4ShJnV+I4iVd0yFLPlLEtVc/JAPw0XpbL9Uj43Bd
// SIG // D1FGd7P4AOG8rAKCX9vAFbO9G9RVS+c5oQ/pI0m8GLhE
// SIG // fEXkwcNyeuBy5yTfv0aZxe/CHFfbg43sTUkwp6uO3+xb
// SIG // n6/83bBm4sGXgXvt1u1L50kppxMopqd9Z4DmimJ4X7Iv
// SIG // hNdXnFy/dygo8e1twyiPLI9AN0/B4YVEicQJTMXUpUMv
// SIG // dJX3bvh4IFgsE11glZo+TzOE2rCIF96eTvSWsLxGoGyY
// SIG // 0uDWiIwLAgMBAAGjggHtMIIB6TAQBgkrBgEEAYI3FQEE
// SIG // AwIBADAdBgNVHQ4EFgQUSG5k5VAF04KqFzc3IrVtqMp1
// SIG // ApUwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYD
// SIG // VR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0j
// SIG // BBgwFoAUci06AjGQQ7kUBU7h6qfHMdEjiTQwWgYDVR0f
// SIG // BFMwUTBPoE2gS4ZJaHR0cDovL2NybC5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0
// SIG // MjAxMV8yMDExXzAzXzIyLmNybDBeBggrBgEFBQcBAQRS
// SIG // MFAwTgYIKwYBBQUHMAKGQmh0dHA6Ly93d3cubWljcm9z
// SIG // b2Z0LmNvbS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0MjAx
// SIG // MV8yMDExXzAzXzIyLmNydDCBnwYDVR0gBIGXMIGUMIGR
// SIG // BgkrBgEEAYI3LgMwgYMwPwYIKwYBBQUHAgEWM2h0dHA6
// SIG // Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvZG9jcy9w
// SIG // cmltYXJ5Y3BzLmh0bTBABggrBgEFBQcCAjA0HjIgHQBM
// SIG // AGUAZwBhAGwAXwBwAG8AbABpAGMAeQBfAHMAdABhAHQA
// SIG // ZQBtAGUAbgB0AC4gHTANBgkqhkiG9w0BAQsFAAOCAgEA
// SIG // Z/KGpZjgVHkaLtPYdGcimwuWEeFjkplCln3SeQyQwWVf
// SIG // Liw++MNy0W2D/r4/6ArKO79HqaPzadtjvyI1pZddZYSQ
// SIG // fYtGUFXYDJJ80hpLHPM8QotS0LD9a+M+By4pm+Y9G6XU
// SIG // tR13lDni6WTJRD14eiPzE32mkHSDjfTLJgJGKsKKELuk
// SIG // qQUMm+1o+mgulaAqPyprWEljHwlpblqYluSD9MCP80Yr
// SIG // 3vw70L01724lruWvJ+3Q3fMOr5kol5hNDj0L8giJ1h/D
// SIG // Mhji8MUtzluetEk5CsYKwsatruWy2dsViFFFWDgycSca
// SIG // f7H0J/jeLDogaZiyWYlobm+nt3TDQAUGpgEqKD6CPxNN
// SIG // ZgvAs0314Y9/HG8VfUWnduVAKmWjw11SYobDHWM2l4bf
// SIG // 2vP48hahmifhzaWX0O5dY0HjWwechz4GdwbRBrF1HxS+
// SIG // YWG18NzGGwS+30HHDiju3mUv7Jf2oVyW2ADWoUa9WfOX
// SIG // pQlLSBCZgB/QACnFsZulP0V3HjXG0qKin3p6IvpIlR+r
// SIG // +0cjgPWe+L9rt0uX4ut1eBrs6jeZeRhL/9azI2h15q/6
// SIG // /IvrC4DqaTuv/DDtBEyO3991bWORPdGdVk5Pv4BXIqF4
// SIG // ETIheu9BCrE/+6jMpF3BoYibV3FWTkhFwELJm3ZbCoBI
// SIG // a/15n8G9bW1qyVJzEw16UM0xghomMIIaIgIBATCBlTB+
// SIG // MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3Rv
// SIG // bjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWlj
// SIG // cm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNy
// SIG // b3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDExAhMzAAAE
// SIG // BGx0Bv9XKydyAAAAAAQEMA0GCWCGSAFlAwQCAQUAoIGu
// SIG // MBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisG
// SIG // AQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMC8GCSqGSIb3
// SIG // DQEJBDEiBCC30OPQYwYvv5f8PTSoqtE1aWTt/++ybwc5
// SIG // Guc51io+YTBCBgorBgEEAYI3AgEMMTQwMqAUgBIATQBp
// SIG // AGMAcgBvAHMAbwBmAHShGoAYaHR0cDovL3d3dy5taWNy
// SIG // b3NvZnQuY29tMA0GCSqGSIb3DQEBAQUABIIBACvPYyM2
// SIG // h1OdoYvZqkdAZOY2loDGav79aD8tn3GYbeWj8Dj3SVyl
// SIG // o1gBKEgZAXS9HkK9YlO7KDcb5dQZxZYXq8SILK1C/BMH
// SIG // jptfx6Jlod+cASttbpKF1ujLoVPv79xagTc+xIa4mq/n
// SIG // FAUbsk2nj2pPVGxg6weGfAQvDyXlqBlUSOIn5xrs0Clt
// SIG // ijqzq3HdH5CpOKkXgf7o8B576NaJ2RYe5B7c+NCTZIb9
// SIG // 5E4RiN4Zfc9vd9eqk5ZJh6TeVFzDGw5cNGm9GSjnuh9t
// SIG // XGWaAJdRXtvHDwzbE9aPVEJkH8mC7USSB0hZbVysDTvo
// SIG // ih2HHT07t6p9JaVcwoRlMcSjCSqhghewMIIXrAYKKwYB
// SIG // BAGCNwMDATGCF5wwgheYBgkqhkiG9w0BBwKggheJMIIX
// SIG // hQIBAzEPMA0GCWCGSAFlAwQCAQUAMIIBWgYLKoZIhvcN
// SIG // AQkQAQSgggFJBIIBRTCCAUECAQEGCisGAQQBhFkKAwEw
// SIG // MTANBglghkgBZQMEAgEFAAQgrf/0PUflW/YWfK/P0up/
// SIG // nRQnFdu+b7Nyo3zOXfb01okCBmditEgvshgTMjAyNTAx
// SIG // MTAxNTU4NDkuMzcxWjAEgAIB9KCB2aSB1jCB0zELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjEtMCsGA1UECxMkTWljcm9zb2Z0
// SIG // IElyZWxhbmQgT3BlcmF0aW9ucyBMaW1pdGVkMScwJQYD
// SIG // VQQLEx5uU2hpZWxkIFRTUyBFU046MzYwNS0wNUUwLUQ5
// SIG // NDcxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1w
// SIG // IFNlcnZpY2WgghH+MIIHKDCCBRCgAwIBAgITMwAAAfdY
// SIG // IHUEyvvC9AABAAAB9zANBgkqhkiG9w0BAQsFADB8MQsw
// SIG // CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQ
// SIG // MA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9z
// SIG // b2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3Nv
// SIG // ZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDAeFw0yNDA3MjUx
// SIG // ODMxMDZaFw0yNTEwMjIxODMxMDZaMIHTMQswCQYDVQQG
// SIG // EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
// SIG // BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
// SIG // cnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJl
// SIG // bGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJzAlBgNVBAsT
// SIG // Hm5TaGllbGQgVFNTIEVTTjozNjA1LTA1RTAtRDk0NzEl
// SIG // MCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2Vy
// SIG // dmljZTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
// SIG // ggIBANDnR0wTaJuv7lymhCj/azyE5E+kMRddbY8wdDZN
// SIG // W8g6T6xUx4Wt4ccEnU3K/GNGt5OhEJcKsukTs+NntEeX
// SIG // g1vnQqEGqYqQyBVDmKd6DbqsF/8XqQExJGNezMlxceq0
// SIG // FtjXFlCVt0KNgLidBzrW5UqSLUGTxph5xqpLfwweORcM
// SIG // ZOlaEr8TXECoShE5Ls67fFOg0XHEJtRXYZjyoA84HHwz
// SIG // zOaPhp824jLustOvQOBB5izJpHnEpFbwZnGfFZ8xR0w5
// SIG // Bi3aZw1eRV41TmwIG0jNHJ6mEhn0ae1RhwUasqLHL0eG
// SIG // 3EPglfaQ42yekua2Z9bgPIUYY9PR7N9x0Xr7eKFgFWBi
// SIG // LYBLBvgawmG6YFjAxCFZwID2RIjwGiPMARnphOH3hJLs
// SIG // +0wMIJEQXFMy4EOLrz6kQ9QPiZLduvqQ6lmEp9DAPI9M
// SIG // 2nEJPavwL3Ij1w/SLdns/pqhM4BUUbCRi7XH/R5LLyvC
// SIG // bHeiOcxUoZaouW6c39WODTojToeUMFtaSLwOYq5Wpe6h
// SIG // YZAHnnmapqKfPrjcWV8RQkBt0d7OaV1vPRYgofa5l61a
// SIG // jgsIHFxSCUAEJJZSrCPlCahqva5kQASc+ZRykxWJhcHD
// SIG // Odillozcd8+qHcM9ofrMWsXsE6HvRqrQ8d/2lPsqjUXA
// SIG // fMNLUl1H/spTeLpOcRxKS6cfmTTbAgMBAAGjggFJMIIB
// SIG // RTAdBgNVHQ4EFgQU30akMz95vT2Vri39afP5nhX5Jpgw
// SIG // HwYDVR0jBBgwFoAUn6cVXQBeYl2D9OXSZacbUzUZ6XIw
// SIG // XwYDVR0fBFgwVjBUoFKgUIZOaHR0cDovL3d3dy5taWNy
// SIG // b3NvZnQuY29tL3BraW9wcy9jcmwvTWljcm9zb2Z0JTIw
// SIG // VGltZS1TdGFtcCUyMFBDQSUyMDIwMTAoMSkuY3JsMGwG
// SIG // CCsGAQUFBwEBBGAwXjBcBggrBgEFBQcwAoZQaHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jZXJ0cy9N
// SIG // aWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENBJTIwMjAx
// SIG // MCgxKS5jcnQwDAYDVR0TAQH/BAIwADAWBgNVHSUBAf8E
// SIG // DDAKBggrBgEFBQcDCDAOBgNVHQ8BAf8EBAMCB4AwDQYJ
// SIG // KoZIhvcNAQELBQADggIBADdGo2nyC3i+kkCDCDAFzNUH
// SIG // esWqHItpjq6UfLylssk7C92/NwO1xi4gG0MU66p171Vl
// SIG // njbLeWEA/LGjvlE4DiyXU3X1AA4S16CvkZcI353YpiCU
// SIG // /TB/bVGFy8yVyoWTNPaLj8DbK5/GDiyKXQIuUz8jfApd
// SIG // dThmUpT/a/CZ76JltNAKCeD5fa5YNBuZXEJJwF6h2vZ0
// SIG // HVqdWcV6jXftCbCppUfLXADV99wpTPTZ2gpSRMS0B4in
// SIG // h1FFrasizJeuU1usETO15Re2Pj05wvHbjVp+Li54Pjjf
// SIG // 2d/RjuqgY+yBGcaKuKN2rxIfW2uN1FOk4M1WWgZvFWgN
// SIG // MEsFHv6aqUzmBVjetly94JfyQtqc3yD8T+ul30SyMWn4
// SIG // wVV5vClQ59nDC/SL0StNrPeNWOfkUeIEgDoS4kEOgNN1
// SIG // TUbqfrKTGtJPl0zwIvtmjB+cWtWY2/yvLvX/TNOVNP21
// SIG // DCVyQz/vsrFqSW1UQ4hxu7M2nGvq9x4lD40CckJdjYjn
// SIG // GExlfw3C6ywgStsxudNxRm9ODeSn9dF4AMBWl5aHeQfX
// SIG // iofeT51ysdizQYC8BvOWp5YYRscQUOZhbCRpAZ9D2T7Q
// SIG // M2cn6/eqsc6adqR/QySXIygg6zJmc4l2s6WuVVTd+gjt
// SIG // ZA1OAAZEmE1zjPEZiV7kJu5lBd21po/oYwCW+Kc+oU+V
// SIG // MIIHcTCCBVmgAwIBAgITMwAAABXF52ueAptJmQAAAAAA
// SIG // FTANBgkqhkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMx
// SIG // EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
// SIG // ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3Jh
// SIG // dGlvbjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2Vy
// SIG // dGlmaWNhdGUgQXV0aG9yaXR5IDIwMTAwHhcNMjEwOTMw
// SIG // MTgyMjI1WhcNMzAwOTMwMTgzMjI1WjB8MQswCQYDVQQG
// SIG // EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
// SIG // BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
// SIG // cnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGlt
// SIG // ZS1TdGFtcCBQQ0EgMjAxMDCCAiIwDQYJKoZIhvcNAQEB
// SIG // BQADggIPADCCAgoCggIBAOThpkzntHIhC3miy9ckeb0O
// SIG // 1YLT/e6cBwfSqWxOdcjKNVf2AX9sSuDivbk+F2Az/1xP
// SIG // x2b3lVNxWuJ+Slr+uDZnhUYjDLWNE893MsAQGOhgfWpS
// SIG // g0S3po5GawcU88V29YZQ3MFEyHFcUTE3oAo4bo3t1w/Y
// SIG // JlN8OWECesSq/XJprx2rrPY2vjUmZNqYO7oaezOtgFt+
// SIG // jBAcnVL+tuhiJdxqD89d9P6OU8/W7IVWTe/dvI2k45GP
// SIG // sjksUZzpcGkNyjYtcI4xyDUoveO0hyTD4MmPfrVUj9z6
// SIG // BVWYbWg7mka97aSueik3rMvrg0XnRm7KMtXAhjBcTyzi
// SIG // YrLNueKNiOSWrAFKu75xqRdbZ2De+JKRHh09/SDPc31B
// SIG // mkZ1zcRfNN0Sidb9pSB9fvzZnkXftnIv231fgLrbqn42
// SIG // 7DZM9ituqBJR6L8FA6PRc6ZNN3SUHDSCD/AQ8rdHGO2n
// SIG // 6Jl8P0zbr17C89XYcz1DTsEzOUyOArxCaC4Q6oRRRuLR
// SIG // vWoYWmEBc8pnol7XKHYC4jMYctenIPDC+hIK12NvDMk2
// SIG // ZItboKaDIV1fMHSRlJTYuVD5C4lh8zYGNRiER9vcG9H9
// SIG // stQcxWv2XFJRXRLbJbqvUAV6bMURHXLvjflSxIUXk8A8
// SIG // FdsaN8cIFRg/eKtFtvUeh17aj54WcmnGrnu3tz5q4i6t
// SIG // AgMBAAGjggHdMIIB2TASBgkrBgEEAYI3FQEEBQIDAQAB
// SIG // MCMGCSsGAQQBgjcVAgQWBBQqp1L+ZMSavoKRPEY1Kc8Q
// SIG // /y8E7jAdBgNVHQ4EFgQUn6cVXQBeYl2D9OXSZacbUzUZ
// SIG // 6XIwXAYDVR0gBFUwUzBRBgwrBgEEAYI3TIN9AQEwQTA/
// SIG // BggrBgEFBQcCARYzaHR0cDovL3d3dy5taWNyb3NvZnQu
// SIG // Y29tL3BraW9wcy9Eb2NzL1JlcG9zaXRvcnkuaHRtMBMG
// SIG // A1UdJQQMMAoGCCsGAQUFBwMIMBkGCSsGAQQBgjcUAgQM
// SIG // HgoAUwB1AGIAQwBBMAsGA1UdDwQEAwIBhjAPBgNVHRMB
// SIG // Af8EBTADAQH/MB8GA1UdIwQYMBaAFNX2VsuP6KJcYmjR
// SIG // PZSQW9fOmhjEMFYGA1UdHwRPME0wS6BJoEeGRWh0dHA6
// SIG // Ly9jcmwubWljcm9zb2Z0LmNvbS9wa2kvY3JsL3Byb2R1
// SIG // Y3RzL01pY1Jvb0NlckF1dF8yMDEwLTA2LTIzLmNybDBa
// SIG // BggrBgEFBQcBAQROMEwwSgYIKwYBBQUHMAKGPmh0dHA6
// SIG // Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMvTWlj
// SIG // Um9vQ2VyQXV0XzIwMTAtMDYtMjMuY3J0MA0GCSqGSIb3
// SIG // DQEBCwUAA4ICAQCdVX38Kq3hLB9nATEkW+Geckv8qW/q
// SIG // XBS2Pk5HZHixBpOXPTEztTnXwnE2P9pkbHzQdTltuw8x
// SIG // 5MKP+2zRoZQYIu7pZmc6U03dmLq2HnjYNi6cqYJWAAOw
// SIG // Bb6J6Gngugnue99qb74py27YP0h1AdkY3m2CDPVtI1Tk
// SIG // eFN1JFe53Z/zjj3G82jfZfakVqr3lbYoVSfQJL1AoL8Z
// SIG // thISEV09J+BAljis9/kpicO8F7BUhUKz/AyeixmJ5/AL
// SIG // aoHCgRlCGVJ1ijbCHcNhcy4sa3tuPywJeBTpkbKpW99J
// SIG // o3QMvOyRgNI95ko+ZjtPu4b6MhrZlvSP9pEB9s7GdP32
// SIG // THJvEKt1MMU0sHrYUP4KWN1APMdUbZ1jdEgssU5HLcEU
// SIG // BHG/ZPkkvnNtyo4JvbMBV0lUZNlz138eW0QBjloZkWsN
// SIG // n6Qo3GcZKCS6OEuabvshVGtqRRFHqfG3rsjoiV5PndLQ
// SIG // THa1V1QJsWkBRH58oWFsc/4Ku+xBZj1p/cvBQUl+fpO+
// SIG // y/g75LcVv7TOPqUxUYS8vwLBgqJ7Fx0ViY1w/ue10Cga
// SIG // iQuPNtq6TPmb/wrpNPgkNWcr4A245oyZ1uEi6vAnQj0l
// SIG // lOZ0dFtq0Z4+7X6gMTN9vMvpe784cETRkPHIqzqKOghi
// SIG // f9lwY1NNje6CbaUFEMFxBmoQtB1VM1izoXBm8qGCA1kw
// SIG // ggJBAgEBMIIBAaGB2aSB1jCB0zELMAkGA1UEBhMCVVMx
// SIG // EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
// SIG // ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3Jh
// SIG // dGlvbjEtMCsGA1UECxMkTWljcm9zb2Z0IElyZWxhbmQg
// SIG // T3BlcmF0aW9ucyBMaW1pdGVkMScwJQYDVQQLEx5uU2hp
// SIG // ZWxkIFRTUyBFU046MzYwNS0wNUUwLUQ5NDcxJTAjBgNV
// SIG // BAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZpY2Wi
// SIG // IwoBATAHBgUrDgMCGgMVAG9vCgxv8V2zQY5jO/56sN24
// SIG // KxDmoIGDMIGApH4wfDELMAkGA1UEBhMCVVMxEzARBgNV
// SIG // BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQx
// SIG // HjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEm
// SIG // MCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENB
// SIG // IDIwMTAwDQYJKoZIhvcNAQELBQACBQDrK4QvMCIYDzIw
// SIG // MjUwMTEwMTEzNDA3WhgPMjAyNTAxMTExMTM0MDdaMHcw
// SIG // PQYKKwYBBAGEWQoEATEvMC0wCgIFAOsrhC8CAQAwCgIB
// SIG // AAICBx8CAf8wBwIBAAICFVUwCgIFAOss1a8CAQAwNgYK
// SIG // KwYBBAGEWQoEAjEoMCYwDAYKKwYBBAGEWQoDAqAKMAgC
// SIG // AQACAwehIKEKMAgCAQACAwGGoDANBgkqhkiG9w0BAQsF
// SIG // AAOCAQEAZtSY/XWtYHQfyw2u3HMdQeSUj+L/V7K1md1Y
// SIG // HlfxJdkcFwoGpDpYnXrS+gdr5cqaMDp+XjDUtZmTMSEF
// SIG // tZeWva8d8eQAicoBug9DRP+DW+qr1kHcOnXaSMkL4xXB
// SIG // VvXg4YVkaO54qhK40uxHXvfpC6Xiyl3PwYxbkJooMpyQ
// SIG // b7kYbxcp1dteLZ154v4HWLBuurXoQPqFOwIF0eyixI9L
// SIG // Y9OUkp3usBQ35pjOax/8u/ICDBvcSw9lht5bBhnj2FoV
// SIG // bPyfKB8igXYHsvbxPAG4mT3Kqty0uGGLgJXmU/dhBlzM
// SIG // mQZz55iWriM3Knh8/EghxxOrD2l+wTcInMZClueD/zGC
// SIG // BA0wggQJAgEBMIGTMHwxCzAJBgNVBAYTAlVTMRMwEQYD
// SIG // VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25k
// SIG // MR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24x
// SIG // JjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBD
// SIG // QSAyMDEwAhMzAAAB91ggdQTK+8L0AAEAAAH3MA0GCWCG
// SIG // SAFlAwQCAQUAoIIBSjAaBgkqhkiG9w0BCQMxDQYLKoZI
// SIG // hvcNAQkQAQQwLwYJKoZIhvcNAQkEMSIEIHdbT5wcJREC
// SIG // JOGleMuZuC/P/R5e0iJ/giIBGLan5cLWMIH6BgsqhkiG
// SIG // 9w0BCRACLzGB6jCB5zCB5DCBvQQgIdqY2mt3GtHnGLob
// SIG // utLmBz/yCpz23nW1UCeUqCB+WeIwgZgwgYCkfjB8MQsw
// SIG // CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQ
// SIG // MA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9z
// SIG // b2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3Nv
// SIG // ZnQgVGltZS1TdGFtcCBQQ0EgMjAxMAITMwAAAfdYIHUE
// SIG // yvvC9AABAAAB9zAiBCDsxLvNnSh0OGB9FhpCEiSgr14y
// SIG // sao86oiHnQ6WF6WD+jANBgkqhkiG9w0BAQsFAASCAgA0
// SIG // V9c7GB6ObfRO/aysnWBvNi/3buKtFi88Q2lfPO8hIAwW
// SIG // +9RLeEnqREP531ADC7e3YcKcQVvmGSi8WseUg07566q/
// SIG // dYVQwxUdAvYKC5vKrIleKR0x/1JW2mscvNdIyHsJ4VSZ
// SIG // AppR6ksBao5xAvO5dQ0cAH2xyFBYdBPSpO7VXfgIW9+s
// SIG // QWvODg0ZoLyN59YrHkeQwIpYQFrqVYnWptD3c2qju+vn
// SIG // 8l9cbZwhhKsOat/5RNPT8zbhN84zvFvkt7R67RCxU5Fg
// SIG // gXaJvL8buYOaSz+NZ4UcvcwGYN7GNxiYd2JBFZSTIy8P
// SIG // cmPgKcgdq7+Lvpu6AzKdqmFfGviBuOCwItrUT5oppP8l
// SIG // JWlighzINQ2bvyitv2F5L2mmeiyTMVvry7ELFHdyPPw/
// SIG // aa/qLMuYJhToHAwKGF2Bmuly+d0qZmoTUBp8MHO76A/p
// SIG // SVy92nj74a0CnGiCZ57AMU2dmNNqxhgkmAvtBqMufc1C
// SIG // E6qVbMKneKRcz02aL4vhsz/C0WXq/O1BykM3l00dVHjZ
// SIG // htVmL8u3J1ppSTeuNEpQ6wBG7QBgLgZrj7AH213hb5yy
// SIG // hW7vrVhm9boXR4XycsoOZBx3KGxB45hNYrMQcGq327xt
// SIG // mI3Dez6H7CZXpiE5GDiwlVJaIHPxsz5P+fitJNfj/weJ
// SIG // MaL9uSdjiV1G1b8vOks78Q==
// SIG // End signature block
