define("userMarksViewModel",["diagnosticsHub","diagnosticsHub-swimlanes","diagnosticsHub-ui","knockout","plugin-vs-v2"],((e,t,r,s,i)=>{return a={103:e=>{const t=document.createElement("script");t.id="IndeterminateProgress",t.innerHTML=atob("PGRpdiBjbGFzcz0ic3Bpbm5lciIgcm9sZT0icHJvZ3Jlc3NiYXIiIGFyaWEtdmFsdWVub3c9IjAiIGFyaWEtdmFsdWVtaW49IjAiIGFyaWEtdmFsdWVtYXg9IjEwMCIgYXJpYS1saXZlPSJhc3NlcnRpdmUiDQogICAgIGRhdGEtYmluZD0ibG9jYWxpemVkQXJpYUxhYmVsOidPdmVybGF5X1Byb2dyZXNzSW5kZXRlcm1pbmF0ZUFyaWFMYWJlbCciPg0KICAgIDxkaXYgY2xhc3M9ImJhcjEiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjIiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjMiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjQiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjUiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjYiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjciPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjgiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjkiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjEwIj48L2Rpdj4NCjwvZGl2Pg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},680:e=>{const t=document.createElement("script");t.id="LoadingView",t.innerHTML=atob("PGRpdiBpZD0icHJvZ3Jlc3MtY29udHJvbCI+DQogICAgPHNwYW4gY2xhc3M9Im1lc3NhZ2UiIGRhdGEtYmluZD0ibG9jYWxpemVkVGV4dDogJ0xvYWRpbmdEYXRhTWVzc2FnZSciPjwvc3Bhbj4NCiAgICA8IS0tIGtvIHRlbXBsYXRlOiB7IG5hbWU6ICdJbmRldGVybWluYXRlUHJvZ3Jlc3MnIH0gLS0+PCEtLSAva28gLS0+DQo8L2Rpdj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},338:e=>{const t=document.createElement("script");t.id="UserMarksRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJkYXRhR3JpZFJvdyIgcm9sZT0icm93IiB0YWJpbmRleD0iLTEiIGRhdGEtYmluZD0iDQogICAgZGF0YUdyaWRSb3dGb2N1czogJHBhcmVudC5mb2N1c2VkUm93KCkgPT09ICRkYXRhLA0KICAgIGNzczogeyBzZWxlY3RlZDogc2VsZWN0ZWQoKSB9Ij4NCiAgICA8dGQgcm9sZT0iZ3JpZGNlbGwiIGNsYXNzPSJsZWZ0LWFsaWduIiBkYXRhLWJpbmQ9InRleHQ6IG1hcmtJZCIgZGF0YS1jb2x1bW5pZD0ibWFya0lkIj48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgY2xhc3M9ImxlZnQtYWxpZ24iIGRhdGEtYmluZD0idGV4dDogbmFtZSIgZGF0YS1jb2x1bW5pZD0ibmFtZSI+PC90ZD4NCiAgICA8dGQgcm9sZT0iZ3JpZGNlbGwiIGRhdGEtYmluZD0idGV4dDogKHRpbWVzdGFtcCAvIDEwMDAwMDAuMCkudG9GaXhlZCgzKSIgZGF0YS1jb2x1bW5pZD0idGltZXN0YW1wIj48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgZGF0YS1iaW5kPSJ0ZXh0OiB0aW1lRW5kICE9PSBudWxsID8gKHRpbWVFbmQgLyAxMDAwMDAwLjApLnRvRml4ZWQoMykgOiBub1RpbWVFbmQiIGRhdGEtY29sdW1uaWQ9InRpbWVFbmQiPjwvdGQ+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0ibGVmdC1hbGlnbiIgZGF0YS1iaW5kPSJ0ZXh0OiBwaWQiIGRhdGEtY29sdW1uaWQ9InBpZCI+PC90ZD4NCiAgICA8dGQgcm9sZT0iZ3JpZGNlbGwiIGNsYXNzPSJsZWZ0LWFsaWduIiBkYXRhLWJpbmQ9InRleHQ6IG1lc3NhZ2UiIGRhdGEtY29sdW1uaWQ9Im1lc3NhZ2UiPjwvdGQ+DQo8L3RyPg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},952:(e,t,r)=>{var s;s=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.UserMarksDetailsViewId=t.MarksAnalyzerId=void 0,t.MarksAnalyzerId=function(){return"D278B2D7-2E05-472F-B474-6DDC62F7245E"},t.UserMarksDetailsViewId=function(){return"BEA3C62C-7870-48B1-91ED-978E6D522C2C"}}.apply(t,[r,t]),void 0===s||(e.exports=s)},766:(e,t,r)=>{var s,i;s=[r,t,r(226)],i=function(e,t,r){"use strict";let s;Object.defineProperty(t,"__esModule",{value:!0}),t.UserMarksMarshaler=void 0,t.UserMarksMarshaler=class{constructor(){s||(s=r.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.UserMarks.UserMarksMarshaler",{},!0))}getDoubleClickTimeMs(){return s._call("getDoubleClickTimeMs")}getColumnSettings(e){return s._call("getColumnSettings",e)}onColumnChanged(e,t){return s._call("onColumnChanged",e,t)}}}.apply(t,s),void 0===i||(e.exports=i)},945:(e,t,r)=>{var s,i;s=[r,t,r(766)],i=function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.UserMarksColumnSettingsProvider=void 0,t.UserMarksColumnSettingsProvider=class{constructor(){this._view="DetailsView",this._marshaler=new r.UserMarksMarshaler}getColumnSettings(){return this._marshaler.getColumnSettings(this._view)}onColumnChanged(e){this._marshaler.onColumnChanged(this._view,e)}}}.apply(t,s),void 0===i||(e.exports=i)},259:(e,t,r)=>{var s,i;s=[r,t,r(28),r(952),r(117),r(881),r(881),r(0),r(881)],i=function(e,t,r,s,i,a,n,o,d){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.UserMarksDAO=void 0;class l{constructor(e,t){this._filterText=r.observable(""),this._dataLoadStatus=r.observable(d.DataLoadEvent.DataLoadStart),this._dataWarehouse=e,this._logger=i.getLogger("UserMarksDAO"),this._timeFilter=r.observable(t),this._rows=a.AsyncComputed((()=>{const e={timeDomain:this.timeFilter(),customDomain:{task:"get-user-marks"}};return this._dataWarehouse.getFilteredData(e,s.MarksAnalyzerId()).then((e=>{this._logger.debug("Data loaded, updating rows");const t=e.marks.map(((t,r)=>{const s=t.pid.toString();let i=t.id;return e.idMap[s]&&e.idMap[s][t.id]&&(i=e.idMap[s][t.id]),new o.UserMarksRowViewModel(t,this,r,i)}));return this._dataLoadStatus(d.DataLoadEvent.DataLoadCompleted),Promise.resolve(t)}),(e=>("Canceled"!==e.name&&this._dataLoadStatus(d.DataLoadEvent.DataLoadFailed),Promise.resolve([]))))}),void 0,[]),this._filteredRows=r.computed((()=>this._filterText()?this.filterRows():this.rows())),this._timeFilter.notifySubscribers(t)}get filterText(){return this._filterText}get timeFilter(){return this._timeFilter}get defaultSortColumnId(){return"timestamp"}get dataLoadStatus(){return this._dataLoadStatus}get rows(){return this._rows}get filteredRows(){return this._filteredRows}getCount(e){throw new Error("Method not implemented.")}getRows(e,t){return this.sort(this._filteredRows(),t)}search(e,t,r,s,i,a,n){throw new Error("Method not implemented.")}sort(e,t,r){r?.throwIfCancellationRequested();const s=l.SortFunc[t.columnId](t.direction);return e.sort(s),Promise.resolve(e)}filter(e,t){throw new Error("Method not implemented.")}filterRows(){const e=this.filterText().toUpperCase();return this._rows().filter((t=>{const r=t.name.toUpperCase().includes(e),s=t.markId.toUpperCase().includes(e),i=t.message.toUpperCase().includes(e);return r||s||i}))}}t.UserMarksDAO=l,l.SortFunc={name:e=>n.SortFunctions.stringSort("name",e),timestamp:e=>n.SortFunctions.numericSort("timestamp",e),message:e=>n.SortFunctions.stringSort("message",e),timeEnd:e=>n.SortFunctions.numericSort("timeEnd",e),pid:e=>n.SortFunctions.numericSort("pid",e)}}.apply(t,s),void 0===i||(e.exports=i)},0:(e,t,r)=>{var s,i;s=[r,t,r(28),r(226),r(117),r(338)],i=function(e,t,r,s,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.UserMarksRowViewModel=void 0,t.UserMarksRowViewModel=class{constructor(e,t,a,n){this._selected=r.observable(!1),this._logger=i.getLogger("UserMarksRowViewModel"),this._visible=r.observable(!0),this._row=e,this._dao=t,this._id=a,this._name=n,this._adjustedTimestampMSec=this._row.timestamp/1e6,this._noTimeEnd=s.Resources.getString("MarksListNoTimeEnd")}get name(){return this._name}get pid(){return this._row.pid}get message(){return this._row.data}get timeEnd(){return this._row.timeEnd}get timestamp(){return this._row.timestamp}get markId(){return this._row.id}get noTimeEnd(){return this._noTimeEnd}get templateName(){return"UserMarksRowView"}get id(){return this._id}get selected(){return this._selected}invoke(){this._logger.debug("UserMarksRowViewModel: Invoke called")}}}.apply(t,s),void 0===i||(e.exports=i)},937:(e,t,r)=>{var s,i;s=[r,t,r(226),r(28),r(952),r(117),r(881),r(881),r(881),r(259),r(881),r(945),r(117),r(766),r(881),r(560),r(117),r(680),r(103)],i=function(e,t,r,s,i,a,n,o,d,l,m,c,u,g,h,p,I){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.UserMarksViewModel=void 0;var M=r.ContextMenu;class b{constructor(){this._viewEventManager=u.getViewEventManager(),this._currentOverlay=s.pureComputed((()=>this.computeOverlay())),this._filterText=s.observable(""),a.loadDataWarehouse().then((e=>(this._dataWarehouse=e,e.getContextService().getGlobalContext()))).then((e=>e.getTimeDomain())).then((e=>{this._userMarksDAO=new l.UserMarksDAO(this._dataWarehouse,e);const t=new o.DataGridHeaderViewModel([{id:"markId",text:r.Resources.getString("MarksListHeaderId"),hideable:!1},{id:"name",text:r.Resources.getString("MarksListHeaderName"),hideable:!1,sortable:m.SortDirection.Asc},{id:"timestamp",text:r.Resources.getString("MarksListHeaderTimestamp"),hideable:!0,sortable:m.SortDirection.Asc},{id:"timeEnd",text:r.Resources.getString("MarksListHeaderTimeEnd"),hideable:!0,sortable:m.SortDirection.Asc},{id:"pid",text:r.Resources.getString("MarksListHeaderProcessId"),hideable:!0,sortable:m.SortDirection.Asc},{id:"message",text:r.Resources.getString("MarksListHeaderMessage"),hideable:!0,sortable:m.SortDirection.Asc}],new c.UserMarksColumnSettingsProvider,this._userMarksDAO.defaultSortColumnId);this._marksGrid=new n.DataGridViewModel(this._userMarksDAO,t,"UserMarksListAriaLabel"),this._marksGrid.onResultChanged(0),this._userMarksDAO.filteredRows.subscribe((()=>{this._marksGrid.onResultChanged(0)})),this._filterText.subscribe((e=>{""===e&&this._userMarksDAO.filterText(this._filterText())})),this._viewEventManager.selectionChanged.addEventListener((e=>{e.isIntermittent||this._userMarksDAO.timeFilter(e.position)})),s.applyBindings(this),this._viewEventManager.detailsViewReady.raiseEvent({Id:i.UserMarksDetailsViewId()})}))}get marksGrid(){return this._marksGrid}get filterText(){return this._filterText}get currentOverlay(){return this._currentOverlay}get filterTooltip(){return r.Resources.getString("MarksListFilterToolTip")}onFilterKeyDown(e,t){return"Enter"===t.key?(this._userMarksDAO.filterText(this._filterText()),this.marksGrid.onResultChanged(1),!1):"Escape"!==t.key||(this.filterText(""),!1)}onKeyDown(e,t){if(!t.ctrlKey||t.keyCode!==p.KeyCodes.C)return!0;const r=d.DataGridUtils.formatDataGridSelectedToText(this.marksGrid);return navigator.clipboard.writeText(r),!1}contextMenu(e,t){const s=e;if("number"!=typeof s.id||0===this._marksGrid.selectedRows().length)return null;const i=[{label:r.Resources.getString("ContextMenu_SetStart"),callback:()=>{const e=this._userMarksDAO.timeFilter().end;this._viewEventManager.selectionChanged.raiseEvent({position:new I.JsonTimespan(I.BigNumber.convertFromNumber(s.timestamp),e),isIntermittent:!1})},type:M.MenuItemType.command},{label:r.Resources.getString("ContextMenu_SetEnd"),callback:()=>{const e=this._userMarksDAO.timeFilter().begin;this._viewEventManager.selectionChanged.raiseEvent({position:new I.JsonTimespan(e,I.BigNumber.convertFromNumber(s.timestamp)),isIntermittent:!1})},type:M.MenuItemType.command},{label:r.Resources.getString("ContextMenu_SetInterval"),callback:()=>{const e=this.marksGrid.selectedRows().map((e=>this.marksGrid.rows()[e])),t=this.getMinMaxTimestamp(e);this._viewEventManager.selectionChanged.raiseEvent({position:new I.JsonTimespan(I.BigNumber.convertFromNumber(t.min),I.BigNumber.convertFromNumber(t.max)),isIntermittent:!1})},type:M.MenuItemType.command,disabled:()=>this.marksGrid.selectedRows().length<2&&null===s.timeEnd}];return M.create(i)}getMinMaxTimestamp(e){let t=Number.MAX_VALUE,r=Number.MIN_VALUE;for(const s of e)s.timestamp<t&&(t=s.timestamp),s.timeEnd&&s.timeEnd>r&&(r=s.timeEnd);return{min:t,max:r}}computeOverlay(){return this._userMarksDAO.dataLoadStatus()===m.DataLoadEvent.DataLoadStart?{name:"LoadingView"}:null}}t.UserMarksViewModel=b,(new g.UserMarksMarshaler).getDoubleClickTimeMs().then((e=>{h.Init(e),new b}))}.apply(t,s),void 0===i||(e.exports=i)},117:t=>{"use strict";t.exports=e},560:e=>{"use strict";e.exports=t},881:e=>{"use strict";e.exports=r},28:e=>{"use strict";e.exports=s},226:e=>{"use strict";e.exports=i}},n={},function e(t){var r=n[t];if(void 0!==r)return r.exports;var s=n[t]={exports:{}};return a[t](s,s.exports,e),s.exports}(937);var a,n}));
// SIG // Begin signature block
// SIG // MIIoKAYJKoZIhvcNAQcCoIIoGTCCKBUCAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // +LNG2nLunn8tfkaBEyu3IqAmQuiRKWfhbEw79sKm+Zeg
// SIG // gg12MIIF9DCCA9ygAwIBAgITMwAABARsdAb/VysncgAA
// SIG // AAAEBDANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTI0MDkxMjIwMTExNFoX
// SIG // DTI1MDkxMTIwMTExNFowdDELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // tCg32mOdDA6rBBnZSMwxwXegqiDEUFlvQH9Sxww07hY3
// SIG // w7L52tJxLg0mCZjcszQddI6W4NJYb5E9QM319kyyE0l8
// SIG // EvA/pgcxgljDP8E6XIlgVf6W40ms286Cr0azaA1f7vaJ
// SIG // jjNhGsMqOSSSXTZDNnfKs5ENG0bkXeB2q5hrp0qLsm/T
// SIG // WO3oFjeROZVHN2tgETswHR3WKTm6QjnXgGNj+V6rSZJO
// SIG // /WkTqc8NesAo3Up/KjMwgc0e67x9llZLxRyyMWUBE9co
// SIG // T2+pUZqYAUDZ84nR1djnMY3PMDYiA84Gw5JpceeED38O
// SIG // 0cEIvKdX8uG8oQa047+evMfDRr94MG9EWwIDAQABo4IB
// SIG // czCCAW8wHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYB
// SIG // BQUHAwMwHQYDVR0OBBYEFPIboTWxEw1PmVpZS+AzTDwo
// SIG // oxFOMEUGA1UdEQQ+MDykOjA4MR4wHAYDVQQLExVNaWNy
// SIG // b3NvZnQgQ29ycG9yYXRpb24xFjAUBgNVBAUTDTIzMDAx
// SIG // Mis1MDI5MjMwHwYDVR0jBBgwFoAUSG5k5VAF04KqFzc3
// SIG // IrVtqMp1ApUwVAYDVR0fBE0wSzBJoEegRYZDaHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jcmwvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNybDBhBggr
// SIG // BgEFBQcBAQRVMFMwUQYIKwYBBQUHMAKGRWh0dHA6Ly93
// SIG // d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY2VydHMvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNydDAMBgNV
// SIG // HRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4ICAQCI5g/S
// SIG // KUFb3wdUHob6Qhnu0Hk0JCkO4925gzI8EqhS+K4umnvS
// SIG // BU3acsJ+bJprUiMimA59/5x7WhJ9F9TQYy+aD9AYwMtb
// SIG // KsQ/rst+QflfML+Rq8YTAyT/JdkIy7R/1IJUkyIS6srf
// SIG // G1AKlX8n6YeAjjEb8MI07wobQp1F1wArgl2B1mpTqHND
// SIG // lNqBjfpjySCScWjUHNbIwbDGxiFr93JoEh5AhJqzL+8m
// SIG // onaXj7elfsjzIpPnl8NyH2eXjTojYC9a2c4EiX0571Ko
// SIG // mhENF3RtR25A7/X7+gk6upuE8tyMy4sBkl2MUSF08U+E
// SIG // 2LOVcR8trhYxV1lUi9CdgEU2CxODspdcFwxdT1+G8YNc
// SIG // gzHyjx3BNSI4nOZcdSnStUpGhCXbaOIXfvtOSfQX/UwJ
// SIG // oruhCugvTnub0Wna6CQiturglCOMyIy/6hu5rMFvqk9A
// SIG // ltIJ0fSR5FwljW6PHHDJNbCWrZkaEgIn24M2mG1M/Ppb
// SIG // /iF8uRhbgJi5zWxo2nAdyDBqWvpWxYIoee/3yIWpquVY
// SIG // cYGhJp/1I1sq/nD4gBVrk1SKX7Do2xAMMO+cFETTNSJq
// SIG // fTSSsntTtuBLKRB5mw5qglHKuzapDiiBuD1Zt4QwxA/1
// SIG // kKcyQ5L7uBayG78kxlVNNbyrIOFH3HYmdH0Pv1dIX/Mq
// SIG // 7avQpAfIiLpOWwcbjzCCB3owggVioAMCAQICCmEOkNIA
// SIG // AAAAAAMwDQYJKoZIhvcNAQELBQAwgYgxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBSb290
// SIG // IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDExMB4XDTEx
// SIG // MDcwODIwNTkwOVoXDTI2MDcwODIxMDkwOVowfjELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjEoMCYGA1UEAxMfTWljcm9zb2Z0
// SIG // IENvZGUgU2lnbmluZyBQQ0EgMjAxMTCCAiIwDQYJKoZI
// SIG // hvcNAQEBBQADggIPADCCAgoCggIBAKvw+nIQHC6t2G6q
// SIG // ghBNNLrytlghn0IbKmvpWlCquAY4GgRJun/DDB7dN2vG
// SIG // EtgL8DjCmQawyDnVARQxQtOJDXlkh36UYCRsr55JnOlo
// SIG // XtLfm1OyCizDr9mpK656Ca/XllnKYBoF6WZ26DJSJhIv
// SIG // 56sIUM+zRLdd2MQuA3WraPPLbfM6XKEW9Ea64DhkrG5k
// SIG // NXimoGMPLdNAk/jj3gcN1Vx5pUkp5w2+oBN3vpQ97/vj
// SIG // K1oQH01WKKJ6cuASOrdJXtjt7UORg9l7snuGG9k+sYxd
// SIG // 6IlPhBryoS9Z5JA7La4zWMW3Pv4y07MDPbGyr5I4ftKd
// SIG // gCz1TlaRITUlwzluZH9TupwPrRkjhMv0ugOGjfdf8NBS
// SIG // v4yUh7zAIXQlXxgotswnKDglmDlKNs98sZKuHCOnqWbs
// SIG // YR9q4ShJnV+I4iVd0yFLPlLEtVc/JAPw0XpbL9Uj43Bd
// SIG // D1FGd7P4AOG8rAKCX9vAFbO9G9RVS+c5oQ/pI0m8GLhE
// SIG // fEXkwcNyeuBy5yTfv0aZxe/CHFfbg43sTUkwp6uO3+xb
// SIG // n6/83bBm4sGXgXvt1u1L50kppxMopqd9Z4DmimJ4X7Iv
// SIG // hNdXnFy/dygo8e1twyiPLI9AN0/B4YVEicQJTMXUpUMv
// SIG // dJX3bvh4IFgsE11glZo+TzOE2rCIF96eTvSWsLxGoGyY
// SIG // 0uDWiIwLAgMBAAGjggHtMIIB6TAQBgkrBgEEAYI3FQEE
// SIG // AwIBADAdBgNVHQ4EFgQUSG5k5VAF04KqFzc3IrVtqMp1
// SIG // ApUwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYD
// SIG // VR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0j
// SIG // BBgwFoAUci06AjGQQ7kUBU7h6qfHMdEjiTQwWgYDVR0f
// SIG // BFMwUTBPoE2gS4ZJaHR0cDovL2NybC5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0
// SIG // MjAxMV8yMDExXzAzXzIyLmNybDBeBggrBgEFBQcBAQRS
// SIG // MFAwTgYIKwYBBQUHMAKGQmh0dHA6Ly93d3cubWljcm9z
// SIG // b2Z0LmNvbS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0MjAx
// SIG // MV8yMDExXzAzXzIyLmNydDCBnwYDVR0gBIGXMIGUMIGR
// SIG // BgkrBgEEAYI3LgMwgYMwPwYIKwYBBQUHAgEWM2h0dHA6
// SIG // Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvZG9jcy9w
// SIG // cmltYXJ5Y3BzLmh0bTBABggrBgEFBQcCAjA0HjIgHQBM
// SIG // AGUAZwBhAGwAXwBwAG8AbABpAGMAeQBfAHMAdABhAHQA
// SIG // ZQBtAGUAbgB0AC4gHTANBgkqhkiG9w0BAQsFAAOCAgEA
// SIG // Z/KGpZjgVHkaLtPYdGcimwuWEeFjkplCln3SeQyQwWVf
// SIG // Liw++MNy0W2D/r4/6ArKO79HqaPzadtjvyI1pZddZYSQ
// SIG // fYtGUFXYDJJ80hpLHPM8QotS0LD9a+M+By4pm+Y9G6XU
// SIG // tR13lDni6WTJRD14eiPzE32mkHSDjfTLJgJGKsKKELuk
// SIG // qQUMm+1o+mgulaAqPyprWEljHwlpblqYluSD9MCP80Yr
// SIG // 3vw70L01724lruWvJ+3Q3fMOr5kol5hNDj0L8giJ1h/D
// SIG // Mhji8MUtzluetEk5CsYKwsatruWy2dsViFFFWDgycSca
// SIG // f7H0J/jeLDogaZiyWYlobm+nt3TDQAUGpgEqKD6CPxNN
// SIG // ZgvAs0314Y9/HG8VfUWnduVAKmWjw11SYobDHWM2l4bf
// SIG // 2vP48hahmifhzaWX0O5dY0HjWwechz4GdwbRBrF1HxS+
// SIG // YWG18NzGGwS+30HHDiju3mUv7Jf2oVyW2ADWoUa9WfOX
// SIG // pQlLSBCZgB/QACnFsZulP0V3HjXG0qKin3p6IvpIlR+r
// SIG // +0cjgPWe+L9rt0uX4ut1eBrs6jeZeRhL/9azI2h15q/6
// SIG // /IvrC4DqaTuv/DDtBEyO3991bWORPdGdVk5Pv4BXIqF4
// SIG // ETIheu9BCrE/+6jMpF3BoYibV3FWTkhFwELJm3ZbCoBI
// SIG // a/15n8G9bW1qyVJzEw16UM0xghoKMIIaBgIBATCBlTB+
// SIG // MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3Rv
// SIG // bjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWlj
// SIG // cm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNy
// SIG // b3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDExAhMzAAAE
// SIG // BGx0Bv9XKydyAAAAAAQEMA0GCWCGSAFlAwQCAQUAoIGu
// SIG // MBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisG
// SIG // AQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMC8GCSqGSIb3
// SIG // DQEJBDEiBCCQLAiikqxGzvADEd8V7YeuIFidNX6moW4u
// SIG // ifXCAPLOxjBCBgorBgEEAYI3AgEMMTQwMqAUgBIATQBp
// SIG // AGMAcgBvAHMAbwBmAHShGoAYaHR0cDovL3d3dy5taWNy
// SIG // b3NvZnQuY29tMA0GCSqGSIb3DQEBAQUABIIBAFvlfmdv
// SIG // ARtajkI8AWIj1oPBGbhWRw7DO9WlYj9Zr0l3bjQZikj+
// SIG // WyGQKlepym+jVEnaPfqAx5BNk9B3w3nXVNPc87z+IegS
// SIG // 4CGy5KR30Tod4MCpQL6b0/NkKa517dps0THVZ9IurSZv
// SIG // zO40YpGJMTBrugHOwehxT7yymd68riX12dxHCXnaD05F
// SIG // 8v7IyccaOXGoEO7tsi3ZuKjpt6e1Rz4tOKPdYEy4aDmm
// SIG // ++Qhe5KW1W+k8vdqUDXr9PPFkd0CdVr0LTCfYD64m0Ul
// SIG // EdTojwzjLjfWK4Y8bqqXcJNsI5ejdAeogeUf7sNyz4Eh
// SIG // 9tWGggUIdKHLowO94Kxit4ElvRKhgheUMIIXkAYKKwYB
// SIG // BAGCNwMDATGCF4Awghd8BgkqhkiG9w0BBwKgghdtMIIX
// SIG // aQIBAzEPMA0GCWCGSAFlAwQCAQUAMIIBUgYLKoZIhvcN
// SIG // AQkQAQSgggFBBIIBPTCCATkCAQEGCisGAQQBhFkKAwEw
// SIG // MTANBglghkgBZQMEAgEFAAQg2dnLJVxKXXepuubMP0/E
// SIG // pLF4IWLp0lWMxrtwdvUdUh8CBmdbDT+7TBgTMjAyNTAx
// SIG // MTAxNTUwMjYuNTk3WjAEgAIB9KCB0aSBzjCByzELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjElMCMGA1UECxMcTWljcm9zb2Z0
// SIG // IEFtZXJpY2EgT3BlcmF0aW9uczEnMCUGA1UECxMeblNo
// SIG // aWVsZCBUU1MgRVNOOjMzMDMtMDVFMC1EOTQ3MSUwIwYD
// SIG // VQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNl
// SIG // oIIR6jCCByAwggUIoAMCAQICEzMAAAHm2UKe6gD4feEA
// SIG // AQAAAeYwDQYJKoZIhvcNAQELBQAwfDELMAkGA1UEBhMC
// SIG // VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcT
// SIG // B1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jw
// SIG // b3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUt
// SIG // U3RhbXAgUENBIDIwMTAwHhcNMjMxMjA2MTg0NTE1WhcN
// SIG // MjUwMzA1MTg0NTE1WjCByzELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjElMCMGA1UECxMcTWljcm9zb2Z0IEFtZXJpY2EgT3Bl
// SIG // cmF0aW9uczEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNO
// SIG // OjMzMDMtMDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNyb3Nv
// SIG // ZnQgVGltZS1TdGFtcCBTZXJ2aWNlMIICIjANBgkqhkiG
// SIG // 9w0BAQEFAAOCAg8AMIICCgKCAgEAvb6YfOLYJbhM5v8K
// SIG // TSpQI3BJRs35bygA2dQ/tnf4nmGBLRdhyjKyhhQzi6S1
// SIG // lhuQxMoim5WCqxNp7eeNDhrt+WcdIFyQRNM1mp2RAIwo
// SIG // 7eHhgYvrmpGbJO9Mx00Bx8nz/gd5tgUkjRT4YLFSD6er
// SIG // 6P/bejnjXsyMF+ROflcBBt+52YBHsUBdn0GWG8UNQGrq
// SIG // g70XV7EqStXYdVAbfRGjLM7rnGkeZzMEDerA4xvfRc3S
// SIG // vQLc25+EppbKC1LUQIf++vLCndGNYTJilR8CF/P+CblE
// SIG // VAUWdCVrtDWEAafJIZLtfEPAgEOdNLRQe1R96Q/M6AOJ
// SIG // XAOyZMUxqDyq7n5vpUWQAOIjIG3C2dj/8UnZyhcVPLy9
// SIG // 9UaDZWSYhi+TKk1778gS8/jET+BJ/TcntTfMf5SQ9bLX
// SIG // TaOcCRvpoF7BP8384NhmlakHMxR4NDZfG6SKpzRVEXkE
// SIG // atwtY1WDAknHoDcx3mLcOTpmf+3lZ0Zo15QrC73bMTs3
// SIG // NWFZ+p2S5EA+ct9R2KwfYiB7rMIWjL9oSTTY1Z3ZKVsv
// SIG // d+DyGblkzJN+tJI1zxcJdlr9U85vbTqwqvPpeNPCiC+i
// SIG // fnn6BjZEfGAdzPrtbWHlQzv03Dmxh8WhhQekGcQFKZ3w
// SIG // eTfzJgTcTDqsxtTfEIsFvILY4zCYhQX+omGKwo7UcBey
// SIG // D3UCxbUCAwEAAaOCAUkwggFFMB0GA1UdDgQWBBTlBDF5
// SIG // 7TeePtdWTPkLu0Oa4NxXPTAfBgNVHSMEGDAWgBSfpxVd
// SIG // AF5iXYP05dJlpxtTNRnpcjBfBgNVHR8EWDBWMFSgUqBQ
// SIG // hk5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3Bz
// SIG // L2NybC9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENB
// SIG // JTIwMjAxMCgxKS5jcmwwbAYIKwYBBQUHAQEEYDBeMFwG
// SIG // CCsGAQUFBzAChlBodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
// SIG // b20vcGtpb3BzL2NlcnRzL01pY3Jvc29mdCUyMFRpbWUt
// SIG // U3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNydDAMBgNVHRMB
// SIG // Af8EAjAAMBYGA1UdJQEB/wQMMAoGCCsGAQUFBwMIMA4G
// SIG // A1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAgEA
// SIG // YW7qIE2qUbLsEpGhTEOncrvGQmFKVkPIiK24uNLVNoSu
// SIG // qR4LtIY9M//cxUUceQ34bpI724wP3UuVWH8c9RCGz5bf
// SIG // PezCdrARjtmC2MGHpXyaQ8GwdF0vWZK6qc6ul/5Zg0A5
// SIG // 9xub3GKWEAieeSy78hZSdfeQFaOFsvFF+ae4PVtzIDR0
// SIG // DKTPhFeuPnLM4+B6OWkJnihrSsu8O9nkWP71g7qba786
// SIG // 7hTZigiLddlHAOQTrF6dT7ZI8dskbAo++w0ppdM1WI6l
// SIG // vyElpKxo8nlSfpIc3LcWi5JJVcAsYoKJA+n5Fm8tIQhC
// SIG // kzkzzM4boDyAHMXB7EdrMdNWEWvaR9s73XbLgRH0hRug
// SIG // o9EErxGfzPZifoeJomkEkewBG1Rg28kSpGJ/NEvtwJkZ
// SIG // Yd2TnvgRaieezl3XiA0h27x8ye6E6hvPepd3lIT7GYOv
// SIG // XzYMU8Zb0TZkRP/utWI+2dbgdF2ED+tK7DC3U5VWBMmV
// SIG // JeTC0y+S76haM2ZUtl6I4uARD+nXVU85hyeKHTmTFk03
// SIG // kNCMJ1hvfL1r/66D3oAq9RutRVa3VyxNwFyH7eGTeGZA
// SIG // 056AIT8Ow2TT0ZUluE21Y/y8NF75y2DcDFAPaLmP8Mfb
// SIG // Xk2ifL05G4GMmjmChc+qzUV2eGn+ntyF8DAn3wmrKSlF
// SIG // wu9mDLuVvC/88k8bDVBIAW0wggdxMIIFWaADAgECAhMz
// SIG // AAAAFcXna54Cm0mZAAAAAAAVMA0GCSqGSIb3DQEBCwUA
// SIG // MIGIMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
// SIG // Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
// SIG // TWljcm9zb2Z0IENvcnBvcmF0aW9uMTIwMAYDVQQDEylN
// SIG // aWNyb3NvZnQgUm9vdCBDZXJ0aWZpY2F0ZSBBdXRob3Jp
// SIG // dHkgMjAxMDAeFw0yMTA5MzAxODIyMjVaFw0zMDA5MzAx
// SIG // ODMyMjVaMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpX
// SIG // YXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYD
// SIG // VQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNV
// SIG // BAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEw
// SIG // MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
// SIG // 5OGmTOe0ciELeaLL1yR5vQ7VgtP97pwHB9KpbE51yMo1
// SIG // V/YBf2xK4OK9uT4XYDP/XE/HZveVU3Fa4n5KWv64NmeF
// SIG // RiMMtY0Tz3cywBAY6GB9alKDRLemjkZrBxTzxXb1hlDc
// SIG // wUTIcVxRMTegCjhuje3XD9gmU3w5YQJ6xKr9cmmvHaus
// SIG // 9ja+NSZk2pg7uhp7M62AW36MEBydUv626GIl3GoPz130
// SIG // /o5Tz9bshVZN7928jaTjkY+yOSxRnOlwaQ3KNi1wjjHI
// SIG // NSi947SHJMPgyY9+tVSP3PoFVZhtaDuaRr3tpK56KTes
// SIG // y+uDRedGbsoy1cCGMFxPLOJiss254o2I5JasAUq7vnGp
// SIG // F1tnYN74kpEeHT39IM9zfUGaRnXNxF803RKJ1v2lIH1+
// SIG // /NmeRd+2ci/bfV+AutuqfjbsNkz2K26oElHovwUDo9Fz
// SIG // pk03dJQcNIIP8BDyt0cY7afomXw/TNuvXsLz1dhzPUNO
// SIG // wTM5TI4CvEJoLhDqhFFG4tG9ahhaYQFzymeiXtcodgLi
// SIG // Mxhy16cg8ML6EgrXY28MyTZki1ugpoMhXV8wdJGUlNi5
// SIG // UPkLiWHzNgY1GIRH29wb0f2y1BzFa/ZcUlFdEtsluq9Q
// SIG // BXpsxREdcu+N+VLEhReTwDwV2xo3xwgVGD94q0W29R6H
// SIG // XtqPnhZyacaue7e3PmriLq0CAwEAAaOCAd0wggHZMBIG
// SIG // CSsGAQQBgjcVAQQFAgMBAAEwIwYJKwYBBAGCNxUCBBYE
// SIG // FCqnUv5kxJq+gpE8RjUpzxD/LwTuMB0GA1UdDgQWBBSf
// SIG // pxVdAF5iXYP05dJlpxtTNRnpcjBcBgNVHSAEVTBTMFEG
// SIG // DCsGAQQBgjdMg30BATBBMD8GCCsGAQUFBwIBFjNodHRw
// SIG // Oi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL0RvY3Mv
// SIG // UmVwb3NpdG9yeS5odG0wEwYDVR0lBAwwCgYIKwYBBQUH
// SIG // AwgwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYD
// SIG // VR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0j
// SIG // BBgwFoAU1fZWy4/oolxiaNE9lJBb186aGMQwVgYDVR0f
// SIG // BE8wTTBLoEmgR4ZFaHR0cDovL2NybC5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0
// SIG // XzIwMTAtMDYtMjMuY3JsMFoGCCsGAQUFBwEBBE4wTDBK
// SIG // BggrBgEFBQcwAoY+aHR0cDovL3d3dy5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXRfMjAxMC0w
// SIG // Ni0yMy5jcnQwDQYJKoZIhvcNAQELBQADggIBAJ1Vffwq
// SIG // reEsH2cBMSRb4Z5yS/ypb+pcFLY+TkdkeLEGk5c9MTO1
// SIG // OdfCcTY/2mRsfNB1OW27DzHkwo/7bNGhlBgi7ulmZzpT
// SIG // Td2YurYeeNg2LpypglYAA7AFvonoaeC6Ce5732pvvinL
// SIG // btg/SHUB2RjebYIM9W0jVOR4U3UkV7ndn/OOPcbzaN9l
// SIG // 9qRWqveVtihVJ9AkvUCgvxm2EhIRXT0n4ECWOKz3+SmJ
// SIG // w7wXsFSFQrP8DJ6LGYnn8AtqgcKBGUIZUnWKNsIdw2Fz
// SIG // Lixre24/LAl4FOmRsqlb30mjdAy87JGA0j3mSj5mO0+7
// SIG // hvoyGtmW9I/2kQH2zsZ0/fZMcm8Qq3UwxTSwethQ/gpY
// SIG // 3UA8x1RtnWN0SCyxTkctwRQEcb9k+SS+c23Kjgm9swFX
// SIG // SVRk2XPXfx5bRAGOWhmRaw2fpCjcZxkoJLo4S5pu+yFU
// SIG // a2pFEUep8beuyOiJXk+d0tBMdrVXVAmxaQFEfnyhYWxz
// SIG // /gq77EFmPWn9y8FBSX5+k77L+DvktxW/tM4+pTFRhLy/
// SIG // AsGConsXHRWJjXD+57XQKBqJC4822rpM+Zv/Cuk0+CQ1
// SIG // ZyvgDbjmjJnW4SLq8CdCPSWU5nR0W2rRnj7tfqAxM328
// SIG // y+l7vzhwRNGQ8cirOoo6CGJ/2XBjU02N7oJtpQUQwXEG
// SIG // ahC0HVUzWLOhcGbyoYIDTTCCAjUCAQEwgfmhgdGkgc4w
// SIG // gcsxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5n
// SIG // dG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
// SIG // aWNyb3NvZnQgQ29ycG9yYXRpb24xJTAjBgNVBAsTHE1p
// SIG // Y3Jvc29mdCBBbWVyaWNhIE9wZXJhdGlvbnMxJzAlBgNV
// SIG // BAsTHm5TaGllbGQgVFNTIEVTTjozMzAzLTA1RTAtRDk0
// SIG // NzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAg
// SIG // U2VydmljZaIjCgEBMAcGBSsOAwIaAxUA4ljQXhSfY72h
// SIG // KzeuA9RvOni9JruggYMwgYCkfjB8MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1T
// SIG // dGFtcCBQQ0EgMjAxMDANBgkqhkiG9w0BAQsFAAIFAOsr
// SIG // HMswIhgPMjAyNTAxMTAwNDEyNTlaGA8yMDI1MDExMTA0
// SIG // MTI1OVowdDA6BgorBgEEAYRZCgQBMSwwKjAKAgUA6ysc
// SIG // ywIBADAHAgEAAgItJTAHAgEAAgIUVTAKAgUA6yxuSwIB
// SIG // ADA2BgorBgEEAYRZCgQCMSgwJjAMBgorBgEEAYRZCgMC
// SIG // oAowCAIBAAIDB6EgoQowCAIBAAIDAYagMA0GCSqGSIb3
// SIG // DQEBCwUAA4IBAQCOtA6GgihO3ZidqnJUVACLFkChDScD
// SIG // I4iIh+xvlQ1AZKbPO7/lMT//h5xtzko7reUamMMyzDIY
// SIG // 4kLlCyvlFMIRatKNGf09tLHKnOh97WG4N5QAxjFLaq7c
// SIG // i4lvI5dX2hEpxkeWgvW5CcndbmJbih4Uioj0ZgHwp+Hd
// SIG // 4GNttrPTUi5A+ieie2G/2Xzc8CyiADoeU4xsUHR2GTOq
// SIG // YddVrIHvcKpdCbPNdq3jsGzLFt3PCjX0u1ND1mi8CLwe
// SIG // 9f0Q47IvvwfzC9dYD5Lb2/D6ysrg5d+hpUW92ZAeWhzv
// SIG // E3jKWQpNOjRp5sLzXpm3i9+ClqKSnmWrTIMofL+BhZ48
// SIG // WXYNMYIEDTCCBAkCAQEwgZMwfDELMAkGA1UEBhMCVVMx
// SIG // EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
// SIG // ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3Jh
// SIG // dGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3Rh
// SIG // bXAgUENBIDIwMTACEzMAAAHm2UKe6gD4feEAAQAAAeYw
// SIG // DQYJYIZIAWUDBAIBBQCgggFKMBoGCSqGSIb3DQEJAzEN
// SIG // BgsqhkiG9w0BCRABBDAvBgkqhkiG9w0BCQQxIgQg2/Ss
// SIG // RG/xJG/wFWxm2sE6JJkMArDcjL+bNmIgMaXpb8wwgfoG
// SIG // CyqGSIb3DQEJEAIvMYHqMIHnMIHkMIG9BCDPu6OGqB6z
// SIG // CWhvIJyztateoSGHEZ6MuhZzgm50g9LGWTCBmDCBgKR+
// SIG // MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5n
// SIG // dG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
// SIG // aWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1p
// SIG // Y3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAAB
// SIG // 5tlCnuoA+H3hAAEAAAHmMCIEIBTMA3FZdd4wuptRZJb3
// SIG // 2gLuVhRS0mgNmplDrDZv0OHWMA0GCSqGSIb3DQEBCwUA
// SIG // BIICAFvf9HsHTBx+JfjIkktMJLl8uAbckzbd7WC4lXMU
// SIG // ASR+MV2oiorwhawIcBulAFUrg5x/pVsV3gqvGYEp/W9l
// SIG // a+JR99XjV3bHmawyz+qVDr3OdgZnPsfgFH6WZyV6e4Zt
// SIG // JlNCUTSxojVLeb09PkbqIP0yobNKngVzkeGaTIhZnGOd
// SIG // 36K8eZ6mDqfksbSVgTUpNyhihNF0jDqdAz2wxKPwgcAd
// SIG // 2si4+O8axxxLIZ7eFgKjctgAXCO6xpZ1fM4u1zs+BWU7
// SIG // pi4kpZPqP1ePblfUEc0E4f+RpRAzJ6vfYVDAyajkSRh4
// SIG // pZpVBEZfdLlH+Vv6YApO0sdhPnuc95G0TgtJeem7G6Xh
// SIG // GqEmH6W9G4qsCiYkMVKqARD3NCqYk/mQtVklxFPLhK8v
// SIG // 2egewNApimQdULd1f1DtI40Ty56Z//WQLTKKRxv/MuUM
// SIG // Hh7nh2Pn8l21UoznkQ/9wI6NJhhQzk52ppN7PLl88oAh
// SIG // VG6HXR8C8PaOOc474ywxy60fkooxM8EsEdzy4fazLKJT
// SIG // A6a5GCperntq+VEOrk7D0XAeQxeNrW/GJsWm234O8KKM
// SIG // Hmihy2psWmmuJwVJwrctdtDBBgw+o0SZ03+DG5lKx/eO
// SIG // 3Drdffxs/hLLRRrtIW347tAJ+oqu7RvtxxpED4JFkTUC
// SIG // wnHrx6/fe674n2a4Q9mcIy1/fx4w
// SIG // End signature block
