# THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.
# BASED ON <%~ it.projectPath %>


function(add_st_target_properties TARGET_NAME)

<% for (const dependency of it.cmake.dependencies) { %>
execute_process(
    COMMAND ${CMAKE_COMMAND} --preset ${PRESET_NAME}
    WORKING_DIRECTORY "<%= dependency.path %>"
)

add_custom_target(
    "<%= dependency.name %>"
    COMMAND ${CMAKE_COMMAND} --build --preset ${PRESET_NAME}
    WORKING_DIRECTORY "<%= dependency.path %>"
)

add_dependencies(${TARGET_NAME} "<%= dependency.name %>")

<% } %>
target_compile_definitions(
    ${TARGET_NAME} PRIVATE
<% for (const definition of it.cmake.symbols) { %>
    "<%= definition %>"
<% } %>
)

target_include_directories(
    ${TARGET_NAME} PRIVATE
<% for (const include of it.cmake.includePaths) { %>
    "<%= include %>"
<% } %>
)

target_compile_options(
    ${TARGET_NAME} PRIVATE
<% for (const option of it.cmake.flags) { %>
    "<%= option %>"
<% } %>
<% for (const option of it.cmake.cpuFlags) { %>
    "<%= option %>"
<% } %>
)

target_link_libraries(
    ${TARGET_NAME} PRIVATE
<% for (const library of it.cmake.libraries) { %>
    "<%= library %>"
<% } %>
)

target_link_directories(
    ${TARGET_NAME} PRIVATE
<% for (const dir of it.cmake.libraryDirectories) { %>
    "<%= dir %>"
<% } %>
)

target_link_options(
    ${TARGET_NAME} PRIVATE
<% for (const option of it.cmake.cpuFlags) { %>
    "<%= option %>"
<% } %>
    -T
<% for (const script of it.cmake.linkerScript) { %>
    "<%= script %>"
<% } %>
<% for (const flag of it.cmake.linkerFlags) { %>
    "<%= flag %>"
<% } %>
)

<% if (it.cmake.debugSourceFiles.length > 0) { %>
set(
    DEBUG_SOURCES
<% for (const source of it.cmake.debugSourceFiles) { %>
    "<%= source %>"
<% } %>
)

<% } %>
<% if (it.cmake.releaseSourceFiles.length > 0) { %>
set(
    RELEASE_SOURCES
<% for (const source of it.cmake.releaseSourceFiles) { %>
    "<%= source %>"
<% } %>
)

<% } %>
<% if (it.cmake.debugSourceFiles.length > 0) { %>
list(TRANSFORM DEBUG_SOURCES REPLACE "(.+)" "$<$<CONFIG:Debug>:\\1>")
<% } %>
<% if (it.cmake.releaseSourceFiles.length > 0) { %>
list(TRANSFORM RELEASE_SOURCES REPLACE "(.+)" "$<$<NOT:$<CONFIG:Debug>>:\\1>")

<% } %>
target_sources(
    ${TARGET_NAME} PRIVATE
<% if (it.cmake.debugSourceFiles.length > 0) { %>
    "${DEBUG_SOURCES}"
<% } %>
<% if (it.cmake.releaseSourceFiles.length > 0) { %>
    "${RELEASE_SOURCES}"
<% } %>
<% for (const path of it.cmake.sourceFiles) { %>
    "<%= path %>"
<% } %>
)

<% if (it.cmake.debugPrebuildCommand) { %>
separate_arguments(
    DEBUG_PREBUILD_COMMAND NATIVE_COMMAND
    "<%= it.cmake.debugPrebuildCommand %>"
)
list(TRANSFORM DEBUG_PREBUILD_COMMAND REPLACE "(.+)" "$<$<CONFIG:Debug>:\\1>")

<% } %>
<% if (it.cmake.releasePrebuildCommand) { %>
separate_arguments(
    RELEASE_PREBUILD_COMMAND NATIVE_COMMAND
    "<%= it.cmake.releasePrebuildCommand %>"
)
list(
    TRANSFORM RELEASE_PREBUILD_COMMAND REPLACE
    "(.+)" "$<$<NOT:$<CONFIG:Debug>>:\\1>"
)

<% } %>
<% if (it.cmake.debugPrebuildCommand || it.cmake.releasePrebuildCommand) { %>
add_custom_command(
    TARGET ${TARGET_NAME} PRE_BUILD
<% if (it.cmake.debugPrebuildCommand) { %>
    COMMAND ${DEBUG_PREBUILD_COMMAND}
<% } %>
<% if (it.cmake.releasePrebuildCommand) { %>
    COMMAND ${RELEASE_PREBUILD_COMMAND}
<% } %>
    WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}/build"
)

<% } %>
add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_SIZE} $<TARGET_FILE:${TARGET_NAME}>
)

add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_OBJCOPY} -O ihex
    $<TARGET_FILE:${TARGET_NAME}> ${TARGET_NAME}.hex
)

add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_OBJCOPY} -O binary
    $<TARGET_FILE:${TARGET_NAME}> ${TARGET_NAME}.bin
)

endfunction()