/*
$DatabaseMustHaveMemOptFilegroupComment$
*/

CREATE TYPE $SchemaQualifiedObjectName$ AS TABLE
(
	Id INT NOT NULL IDENTITY PRIMARY KEY NONCLUSTERED HASH WITH (BUCKET_COUNT=131072), 
	Name VARCHAR(128)
) WITH (MEMORY_OPTIMIZED = ON)