'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'
'     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
'     der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class $classname$

    '''<summary>
    '''form1-Steuerelement
    '''</summary>
    '''<remarks>
    '''Automatisch generiertes Feld.
    '''Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
End Class
